### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by elias-fauser** [hakku276/personalspace-rest#2]
@hakku276 [https://github.com/hakku276/personalspace-rest/blob/master/src/main/java/com/example/personalspace/Preference.java#L16](url) seems to throw the Cast Error. JSONObject appearently just serializes to 10.0 to an Integer 10 and this causes the 500.

**Comment by hakku276** [comment]
i'll have a look at it!! But i think i had covered this in a unit test!! i'll go through this tomorrow
